BC_INIT: false
DAPG_LAM0: 0.1
DAPG_LAM1: 0.99
DEMO_FILE: ../demonstrations/relocate-mug.pkl
ENV_NAME: relocate-mug-0.8
JOB_DIR: ./training_log
JOB_NAME: trpo
NUM_ITER: 2000
POLICY_INIT_LOG_STD: 0.0
POLICY_WS:
- 32
- 32
RNG_SEED: 200
SAVE_FREQ: 100
USE_DAPG: true
NUM_CPU: 10
